### ISSUE TITLE
Getting error while the client 

### ISSUE THREAD

**Issue by nehatkkhan786** [RadiBytes/python-whatsapp-bot#3]
(venv) abdulrasid@ABDULs-MacBook-Pro testingWhatsapp % python testbot.py 
Traceback (most recent call last):
  File "testbot.py", line 1, in <module>
    from python_whatsapp_bot import Whatsapp
  File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/__init__.py", line 1, in <module>
    from .whatsapp import Whatsapp
  File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/whatsapp.py", line 1, in <module>
    from .dispatcher import Dispatcher, Update
  File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/dispatcher.py", line 3, in <module>
    from .markup import Reply_markup
  File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/markup.py", line 24, in <module>
    class Inline_keyboard(Reply_markup):
  File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/markup.py", line 28, in Inline_keyboard
    def __init__(self, inline_buttons: Union[list[str], list[Inline_button]]):
TypeError: 'type' object is not subscriptable
(venv) abdulrasid@ABDULs-MacBook-Pro testingWhatsapp %

**Comment by Radi-dev** [comment]
> (venv) abdulrasid@ABDULs-MacBook-Pro testingWhatsapp % python testbot.py Traceback (most recent call last): File "testbot.py", line 1, in from python_whatsapp_bot import Whatsapp File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/**init**.py", line 1, in from .whatsapp import Whatsapp File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/whatsapp.py", line 1, in from .dispatcher import Dispatcher, Update File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/dispatcher.py", line 3, in from .markup import Reply_markup File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/markup.py", line 24, in class Inline_keyboard(Reply_markup): File "/Users/abdulrasid/Desktop/testingWhatsapp/venv/lib/python3.8/site-packages/python_whatsapp_bot/markup.py", line 28, in Inline_keyboard def **init**(self, inline_buttons: Union[list[str], list[Inline_button]]): TypeError: 'type' object is not subscriptable (venv) abdulrasid@ABDULs-MacBook-Pro testingWhatsapp %

Can you run the installation command again to be sure the latest version of the library is installed.
`pip3 install --upgrade python-whatsapp-bot`

**Comment by RadiBytes** [comment]
You may want to upgrade your python version to 3.9 or later
