### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by proxsystem** [RadiBytes/python-whatsapp-bot#4]
Hello python-whatsapp-bot      0.0.91

`Traceback (most recent call last):
  File "wa.py", line 1, in <module>
    from python_whatsapp_bot import Whatsapp
  File "/usr/local/lib/python3.8/dist-packages/python_whatsapp_bot/__init__.py", line 1, in <module>
    from .whatsapp import Whatsapp
  File "/usr/local/lib/python3.8/dist-packages/python_whatsapp_bot/whatsapp.py", line 1, in <module>
    from .dispatcher import Dispatcher, Update
  File "/usr/local/lib/python3.8/dist-packages/python_whatsapp_bot/dispatcher.py", line 3, in <module>
    from .markup import Reply_markup
  File "/usr/local/lib/python3.8/dist-packages/python_whatsapp_bot/markup.py", line 24, in <module>
    class Inline_keyboard(Reply_markup):
  File "/usr/local/lib/python3.8/dist-packages/python_whatsapp_bot/markup.py", line 28, in Inline_keyboard
    def __init__(self, inline_buttons: Union[list[str], list[Inline_button]]):
TypeError: 'type' object is not subscriptable
`

**Comment by RadiBytes** [comment]
Updating your python version would solve this issue. It is due to annotation syntax used in the project that is only supported by versions 3.9 and later
